---
- hosts: localhost
  become: no
  connection: local
  vars:
    configure_dotfiles: true
    dotfiles_repo: https://github.com/thomascrowley/dotfiles.git
    dotfiles_repo_local_destination: ~/.dotfiles
    dotfiles_repo_version: main
    dotfiles_files:
      - .p10k.zsh
      - .vimrc
      - .zshrc
      - .gitconfig
      - .config/starship.toml
    homebrew_use_brewfile: true
    homebrew_brewfile_dir: '~/.dotfiles'

    homebrew_installed_packages:
      - starship

  roles:
    - role: touchid_sudo
    - role: geerlingguy.mac.homebrew
    - role: ohmyzsh
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: gitconfig
    - role: fonts
    # - scripts
