---
- hosts: localhost
  become: no
  connection: local

  vars_files:
    - secrets.yml
  vars:
    homebrew_use_brewfile: true
    homebrew_brewfile_dir: '~/.dotfiles'

    # homebrew_installed_packages:
    #   - mysql

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - ohmyzsh
    - dotfiles
    - fonts
    - scripts
